services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    hostname: sql1
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123*"
      MSSQL_DB: ecommerce
      MSSQL_USER: Kobeissi
      MSSQL_PASSWORD: 7ellowEl7akey
